---
application:
  name: "test"
  project: "test"
  organization: "QoveryCommunity"
databases:
  - type: "MONGODB"
    name: "shopper"
    version: "4.4"
routers:
  - name: "main-test"
    routes:
      - application_name: "test"
        paths:
          - "/*"
